import type { UserPreference } from '@/types/models';

export interface WorkspaceUiCopy {
    common: {
        workspace_intelligence: string;
        all: string;
        today: string;
        system: string;
        task: string;
        tasks: string;
        project: string;
        projects: string;
        read: string;
        unread: string;
        filters: string;
    };
    activity: {
        title: string;
        description: string;
        total_actions: string;
        contributors: string;
        recent_changes: string;
        filter_all: string;
        filter_created: string;
        filter_updated: string;
        filter_completed: string;
        showing: string;
        empty_title: string;
        empty_description: string;
        today: string;
        yesterday: string;
        event_created: string;
        event_updated: string;
        event_completed: string;
        event_uncompleted: string;
        event_deleted: string;
        event_restored: string;
        event_archived: string;
        event_unarchived: string;
        event_pinned: string;
        event_unpinned: string;
        event_favorited: string;
        event_unfavorited: string;
        event_attached: string;
        event_detached: string;
        event_changed: string;
        subject_todo: string;
        subject_project: string;
        subject_workspace: string;
        subject_item: string;
    };
    notifications: {
        title: string;
        description: string;
        total: string;
        unread: string;
        cleared: string;
        all_tab: string;
        unread_tab: string;
        mark_all: string;
        marked_all: string;
        mark_read: string;
        read_status: string;
        unread_status: string;
        empty_title: string;
        empty_description: string;
        empty_unread_title: string;
        empty_unread_description: string;
        fallback_title: string;
        fallback_body: string;
    };
    calendar: {
        title: string;
        description: string;
        scheduled: string;
        due_today: string;
        overdue: string;
        month: string;
        week: string;
        agenda: string;
        go_today: string;
        previous_period: string;
        next_period: string;
        next_up: string;
        next_up_description: string;
        no_tasks: string;
        no_upcoming: string;
        more: string;
        priority_urgent: string;
        priority_high: string;
        priority_medium: string;
        priority_low: string;
        priority_none: string;
        status_pending: string;
        status_in_progress: string;
        status_completed: string;
        weekdays: string[];
    };
    projects: {
        title: string;
        description: string;
        total: string;
        active: string;
        archived: string;
        task_count: string;
        new_project: string;
        workspace: string;
        collection: string;
        no_description: string;
        open_project: string;
        empty_title: string;
        empty_description: string;
        create_first: string;
        create_title: string;
        create_description: string;
        name: string;
        name_placeholder: string;
        description_label: string;
        description_placeholder: string;
        color: string;
        icon: string;
        cancel: string;
        create: string;
        creating: string;
        created: string;
        create_failed: string;
        name_required: string;
        icon_folder: string;
        icon_briefcase: string;
        icon_code: string;
        icon_palette: string;
        icon_book: string;
        icon_star: string;
        icon_rocket: string;
        icon_globe: string;
    };
}

export interface WorkspaceUiPageProps {
    [key: string]: unknown;
    workspaceUi: WorkspaceUiCopy;
    preferences: UserPreference | null;
}
